namespace DeltaWare.SDK.Serialization.Html.Enums
{
    public enum ElementType
    {
        Div,
        Base,
        Head,
        Link,
        Meta,
        Style,
        Title,
        Body,
        Address,
        Article,
        Aside,
        Header,
        Footer,
        H1,
        H2,
        H3,
        H4,
        H5,
        H6,
        Main,
        Nav,
        Section,
        Html,
        Table,
        Tr,
        Td,
        P
    }
}